version: '3.7'

services:
    app:
        build: 
            context: .
        volumes: 
            - static_data:/vol/web
            - ../RobotixWeb21:/RobotixWeb21
        environment: 
            - SECRET_KEY=o!m3w+(x3q3_c9*bpe))v%5=8w_)&o_s4b*z=p-ij(#*^v%vob
            - ALLOWED_HOST=3.16.128.166
        depends_on:
            - db
    proxy:
        build:
            context: ./proxy
        volumes: 
            - static_data:/vol/static
        ports:
            - "80:80"
        depends_on: 
            - app
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=robot
            - POSTGRES_PASSWORD=django
            - POSTGRES_DB=robotixdb3

    redis:
        image: redis:alpine

    celery:
        restart: always
        build:
            context: .
        command: celery -A RobotixWeb worker -l info
        volumes:
        - ../RobotixWeb21:/RobotixWeb21
        environment:
            - DB_HOST=db
            - DB_NAME=robotixdb3
            - DB_USER=robot
            - DB_PASS=robotixdb3
        depends_on:
            - db
            - redis
            - app
volumes:
    postgres_data:
    static_data: