version: '3.7'

services: 
    app:
        build: 
            context: .
        ports:
            - "8000:8000"
        volumes: 
            - ../RobotixWeb21:/RobotixWeb21
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DEBUG=1
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=robot
            - POSTGRES_PASSWORD=django
            - POSTGRES_DB=robotixdb3
volumes:
    postgres_data: