version: '3.7'

services:
    app:
        build: 
            context: .
        volumes: 
            - static_data:/vol/web
            - ../RobotixWeb21:/RobotixWeb21
        environment: 
            - SECRET_KEY=o!m3w+(x3q3_c9*bpe))v%5=8w_)&o_s4b*z=p-ij(#*^v%vob
            - ALLOWED_HOST=127.0.0.1,localhost
    proxy:
        build:
            context: ./proxy
        volumes: 
            - static_data:/vol/static
        ports:
            - "8080:8080"
        depends_on: 
            - app

volumes:
    static_data: