version: '3.7'

services: 
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app/backend/
        command: >
            sh -c "python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DEBUG=1
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=robot
            - POSTGRES_PASSWORD=django
            - POSTGRES_DB=robotixdb3

    redis:
        image: redis:alpine
    celery_beat:
        build:
            context: .
        restart: on-failure
        volumes:
            - .:/app/backend/
        command: celery -A RobotixWeb beat -l info 
        environment:
            - DB_HOST=db
            - DB_NAME=robotixdb3
            - DB_USER=robot
            - DB_PASS=robotixdb3
            - SECRET_KEY=b8oypie)*b$pt6w#*$kvjjzejj5^d^2nek(bn0&lf8sac1zg-d
        depends_on:
            - db
            - redis
            - app

    celery_worker:
        build:
            context: .
        restart: always
        command: celery -A RobotixWeb worker -l info
        volumes:
            - .:/app/backend/
        environment:
            - DB_HOST=db
            - DB_NAME=robotixdb3
            - DB_USER=robot
            - DB_PASS=robotixdb3
            - SECRET_KEY=b8oypie)*b$pt6w#*$kvjjzejj5^d^2nek(bn0&lf8sac1zg-d
        depends_on:
            - db
            - redis
            - app
volumes:
    postgres_data: